handlers=java.util.logging.ConsoleHandler,jason.runtime.MASConsoleLogHandler
.level=INFO
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
jason.runtime.MASConsoleLogHandler.level=INFO
jason.runtime.MASConsoleLogHandler.formatter=jason.runtime.MASConsoleLogFormatter
jason.runtime.MASConsoleLogHandler.tabbed=true
